### PR TITLE
Unify naming

### PR DESCRIPTION
**Pull request by znicholls**
Adds a test to see if output variable naming is (somewhat) uniform. We can switch to completely matching the RCMIP conventions in future (see #30)

- [x] Tests added
- [x] Documentation added
- [x] Example added (in the documentation, to an existing notebook, or in a new notebook) (N/A)
- [x] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/openscm/openscm-runner/pull/XX>`_) Added feature which does something``)

### CODE REVIEW

**Comment by znicholls** [comment]
@lewisjared @chrisroadmap @maritsandstad I propose using this as a way to make sure we get all the names consistent across the adapters in future. I've fixed it for MAGICC and FaIR here. @maritsandstad let's incorporate these changes into #24 together next week (along with other updates for the Cicero-SCM adapter).

**Comment by maritsandstad** [comment]
Hi @znicholls,
Will this PR be merged in now, so I can merge it in from there to my fork? Otherwise I'm a bit afraid to merge in again, in case this will be rebased before merging in, and then my PR can't be merged in again (without some effort at least...)

**Comment by znicholls** [comment]
> Hi @znicholls,
> Will this PR be merged in now, so I can merge it in from there to my fork? Otherwise I'm a bit afraid to merge in again, in case this will be rebased before merging in, and then my PR can't be merged in again (without some effort at least...)

Yes best hold off for now. This could be a bit fiddly to get right

**Review by lewisjared — COMMENTED** [review]
Will it be easier to support both "Surface Temperature" and "Surface Air Temperature Change" etc for a version or 2 to aid the migration? These names are getting looong...

**Comment by znicholls** [comment]
> Will it be easier to support both "Surface Temperature" and "Surface Air Temperature Change" etc for a version or 2 to aid the migration? These names are getting looong

Could do that. We could also just add a function e.g. `shorten_rcmip_names` which users can apply to the output of `run`?

**Comment by lewisjared** [comment]
Up to you really. I don't use the runner except for in the climate-assessment so the splash zone might not be too bad. It might be needed more when we make the switch with pymagicc.

The `shorten_rcmip_names` is a future feature, something like the CF long_name and standard_name differentiation. We will need to collate a list of the supported variable names one day.

**Comment by znicholls** [comment]
> It might be needed more when we make the switch with pymagicc.

Yep this is part of my attempt to pull everything back onto consistent naming schemes. 

> The `shorten_rcmip_names` is a future feature, something like the CF long_name and standard_name differentiation. We will need to collate a list of the supported variable names one day.

Yep 100%

I'll merge this and make an issue for the shortening feature

**Pull request merged**
