### PR TITLE
Extra aerosol diags

### PR DESCRIPTION
**Pull request by chrisroadmap**
Get individual aerosol forcing species from FaIR as requested by AR6 WG3.

- [x] Tests added
- [x] Documentation added
- [x] Example added (in the documentation, to an existing notebook, or in a new notebook)
- [x] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/openscm/openscm-runner/pull/XX>`_) Added feature which does something``)

### CODE REVIEW

**Comment by znicholls** [comment]
can you rebase on #15 so the CI triggers (should work now...)?

**Comment by chrisroadmap** [comment]
Right should be good to go. By the way, consider specifying the required version of `black` for development. Sometimes the GitHub actions use 20.8, sometimes 19.10, and a couple of files in the magicc_adaptor seem to be sensitive to the choice and tests fail.

**Review by znicholls — APPROVED** [review]
Lgtm. Do you want to explicitly test that the new variables come through or are you not worried?

**Comment by znicholls** [comment]
Yep it’s now pinned in master (look at the dev requirements in setup.py, although i guessing you’re not using the makefile)

**Comment by chrisroadmap** [comment]
> Lgtm. Do you want to explicitly test that the new variables come through or are you not worried?

It should be fine - the total aerosol direct effect included these zero contributions from nitrate and SOA anyway. Thought I'd put them in in case I find a plausible nitrate scheme in the next 2 weeks (read: no)

**Pull request merged**
