### PR TITLE
Add ciceroscm py

### PR DESCRIPTION
**Pull request by maritsandstad**
Adding ciceroscm, this time with a branch with correct origin...

- [x] Tests added
- [x] Documentation added
- [x] Example added (in the documentation, to an existing notebook, or in a new notebook)
- [ ] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/openscm/openscm-runner/pull/XX>`_) Added feature which does something``)

### CODE REVIEW

**Comment by maritsandstad** [comment]
Magicc issues are back, not sure what I did to trigger them...

**Comment by znicholls** [comment]
> Magicc issues are back, not sure what I did to trigger them...

Just bad luck, re-running now

**Comment by maritsandstad** [comment]
The install still doesn't seem to work... The utils_templates in ciceroscm_py_adapter is a symlink to the one in ciceroscm_adapter, should I change that?

**Comment by znicholls** [comment]
> The install still doesn't seem to work... The utils_templates in ciceroscm_py_adapter is a symlink to the one in ciceroscm_adapter, should I change that?

Yep let's try changing that first (error message is a bit cryptic to me too)

**Comment by maritsandstad** [comment]
That seems to have solved it

**Comment by maritsandstad** [comment]
I'll try to add a notebook as well and fix so there's a bit more flexibility running through

**Comment by maritsandstad** [comment]
I think this is mostly how I want it now, but maybe you want to wait for ciceroscmpy to be on pip? I mostly managed to fix that (I think), just need to settle on a version number....

**Comment by maritsandstad** [comment]
Hi @znicholls, ciceroscm is no on pypi: https://pypi.org/project/ciceroscm/ so I tried to update to reflect. Magicc issues are back though, maybe the are solved if  I merge in from master again. Otherwise this can hopefully get a review and be merged in in the seminear future?

**Comment by rgieseke** [comment]
> Magicc issues are back though, maybe the are solved if I merge in from master again. 

Seems to be an issue with downloading the MAGICC binary:

```
Connecting to www.magicc.org (www.magicc.org)|34.148.97.127|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://magicc.org/api/download?type=MAGICC7&*** [following]
--2022-08-17 12:13:22--  https://magicc.org/api/download?type=MAGICC7&***
Resolving magicc.org (magicc.org)... 75.2.60.5
Connecting to magicc.org (magicc.org)|75.2.60.5|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-08-17 12:13:26 ERROR 500: Internal Server Error.
```

Since the download location is set as an environment variable (https://github.com/openscm/openscm-runner/blob/daa497f084a37206557e35d6c0d74451df1ee13a/.github/workflows/ci-cd-workflow.yml#L74) I don't think it has anything to do with merging from the main branch again.

**Comment by maritsandstad** [comment]
You are right @rgieseke, there also wasn't really anything to merge in...

**Comment by maritsandstad** [comment]
I'll be fixing some version stuff though, shouldn't take long, but it won't fix anything magicc related...

**Comment by rgieseke** [comment]
I triggered a re-run of the CI and it fetched the binary, but now something else seems to have errored on macOS.

**Comment by maritsandstad** [comment]
Ok, version stuff fixed, I'm mostly happy with this now (barring magicc issues I really don't know how to deal with). If there is something else that needs fixing before this can be merged in, let me know.

**Comment by rgieseke** [comment]
Yeah, seems to be an issue with MAGICC's Fortran libraries on macOS:
```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib
  Referenced from: /Users/runner/work/openscm-runner/openscm-runner/bin/magicc/magicc-v7.5.3/bin/magicc-darwin-amd64
  Reason: image not found
ImportError while loading conftest '/Users/runner/work/openscm-runner/openscm-runner/tests/conftest.py'.
tests/conftest.py:50: in <module>
    MAGICC_VERSION = MAGICC7.get_version()
src/openscm_runner/adapters/magicc7/magicc7.py:213: in get_version
    return check_output([cls._executable(), "--version"]).decode("utf-8").strip()
../../../hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py:424: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
../../../hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py:528: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '['bin/magicc/magicc-v7.5.3/bin/magicc-darwin-amd64', '--version']' died with <Signals.SIGABRT: 6>.
Error: Process completed with exit code 4.
```
Maybe there is a mismatch of required libraries for the compiled downloaded version and what's available on the CI images.

**Comment by lewisjared** [comment]
I fixed this in #79. The mac ci image changed and the gfortran dylib was moved/not exposed in the same way. 

I'm not an expert with making Mac binarys that work anywhere so there might have been something we could fix at compile time

**Comment by rgieseke** [comment]
Thanks @lewisjared!
I've merged #79 so after merging the main branch and fixing the conflicts this should hopefully work, @maritsandstad

**Comment by maritsandstad** [comment]
Thank you @lewisjared and @rgieseke!

Things seem to all go green now;-)

**Review by znicholls — APPROVED** [review]
LGTM! Merge if you're happy @maritsandstad

**Comment by maritsandstad** [comment]
> LGTM! Merge if you're happy @maritsandstad

I'm very happy ;-)

**Comment by znicholls** [comment]
As long as nothing explodes, this should be released as part of v0.11.0 https://github.com/openscm/openscm-runner/actions/runs/2881581512

**Pull request merged**
