### PR TITLE
FaIR 1.6.0 adapter

### PR DESCRIPTION
**Pull request by chrisroadmap**
Adds the FaIR model adapter to openscm-runner on top of the MAGICC7 adapter at v1.6.0

- [x] Tests added
- [x] Documentation added
- [x] Example added (in the documentation, to an existing notebook, or in a new notebook)
- [x] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/openscm/openscm-runner/pull/XX>`_) Added feature which does something``)

### CODE REVIEW

**Comment by chrisroadmap** [comment]
Right, the only thing failing now is the "deploy to pypi" which I'm not sure how to handle. I set the linter to avoid duplicates of 7 lines. Other than this there should be no surprises.

**Comment by chrisroadmap** [comment]
@znicholls actually you might want to hold off until I put in GMST

**Comment by znicholls** [comment]
> Right, the only thing failing now is the "deploy to pypi"

Don't worry about that, my job. Everything else should be good to go.

**Comment by chrisroadmap** [comment]
> @znicholls actually you might want to hold off until I put in GMST

To do (in order):
- (me) confirm GMST variable name
- (me) update and merge this https://github.com/chrisroadmap/openscm-runner/pull/3
- (you, then me) merge this https://github.com/OMS-NetZero/FAIR/pull/78 (see my comment on scmdata version)
- (you, then me) rebase then merge this https://github.com/chrisroadmap/openscm-runner/pull/2
- increment fair version to 1.6.0

**Comment by znicholls** [comment]
lgtm

**Comment by znicholls** [comment]
Rebased and merged in #12

**Pull request closed without merging**
